runtime: python27
api_version: 1
threadsafe: yes

module: blob-migrator

includes:
- mapreduce/include.yaml

libraries:
- name: webob
  version: "1.2.3"
- name: webapp2
  version: "2.5.1"
- name: jinja2
  version: "2.6"

builtins:
- deferred: on

handlers:
- url: /static
  static_dir: static

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
  expiration: 1d

- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico
  expiration: 1d

- url: /_ah/queue/deferred/.*
  script: google.appengine.ext.deferred.deferred.application
  login: admin

- url: /_ah/pipeline.*
  script: pipeline.handlers._APP
  login: admin

- url: /.*
  script: main.APP
  login: admin
